// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'tokens/colors';
import fontSizes from 'tokens/fontSizes';
import fontFamilies from 'tokens/fontFamilies';
import fontWeights from 'tokens/fontWeights';
import lineHeights from 'tokens/lineHeights';

const ParagraphCss = `
color: ${colors.black};
font-size: ${fontSizes.paragraph};
font-family: ${fontFamilies.regular};
font-weight: ${fontWeights.regular};
line-height: ${lineHeights.xs};
text-align: left;
`;

export default ParagraphCss;