// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
 "bold": "HelveticaNeue-Bold",
 "medium": "HelveticaNeue-Medium",
 "regular": "HelveticaNeue",
 "light": "HelveticaNeue-Light"
}

module.exports = fontFamilies;