// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const letterSpacings = {
 "tight": "-1.08px",
 "wide": "1.20px",
 "regular": "0px"
}

export default letterSpacings;