// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const lineHeights = {
 "xs": "1.00",
 "s": "1.35",
 "m": "1.45",
 "l": "1.65"
}

export default lineHeights;