// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const mediaQueries = {
 "mobilesm": "320px",
 "mobilemd": "480px",
 "mobilelg": "580px",
 "mobilemax": "767px",
 "tabletmin": "768px",
 "tabletmax": "1024px",
 "desktopmd": "1180px",
 "desktoplg": "1440px",
 "wide": "1920px"
}

export default mediaQueries;