// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const mediaQueries = {
 "mobileSm": "320px",
 "mobileMd": "480px",
 "mobileLg": "580px",
 "mobileMax": "767px",
 "tabletMin": "768px",
 "tabletMax": "1024px",
 "desktopMd": "1180px",
 "desktopLg": "1440px",
 "wide": "1920px"
}

export default mediaQueries;