// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const shadows = {
 "deepMulti": "0px 4px 20px rgba(0, 0, 0, 0.1), 0px 4px 4px rgba(0, 0, 0, 0.17)",
 "deep": "3px 3px 3px rgba(196, 196, 196, 0.75)",
 "medium": "0px 0px 5px rgba(0, 0, 0, 0.5)",
 "soft": "0px 0px 5px rgba(196, 196, 196, 1)"
}

export default shadows;